class MBTIData {
  final String type;
  final String description;
  final String mascotImage;
  final String mascotRegion;
  final String mascotName;
  final String bestMatchType;
  final String bestMatchDescription;
  final String bestMatchName;
  final String bestMatchRegion;
  final String bestMatchImage;
  final String worstMatchType;
  final String worstMatchDescription;
  final String worstMatchImage;
  final String worstMatchName;
  final String worstMatchRegion;
  final List<String> traits;
  final List<String> besttraits;
  final List<String> worsttraits;

  MBTIData({
    required this.type,
    required this.description,
    required this.mascotImage,
    required this.mascotName,
    required this.mascotRegion,
    required this.bestMatchType,
    required this.bestMatchDescription,
    required this.bestMatchImage,
    required this.bestMatchName,
    required this.bestMatchRegion,
    required this.worstMatchType,
    required this.worstMatchDescription,
    required this.worstMatchImage,
    required this.worstMatchName,
    required this.worstMatchRegion,
    required this.traits,
    required this.besttraits,
    required this.worsttraits,
  });
}

final List<MBTIData> mbtiDataList = [
  MBTIData(
    type: 'ISTJ',
    description: '꼼꼼한 계획형 여행자',
    mascotImage: 'assets/istj.png',
    mascotName: '또록이',
    mascotRegion: '사천시',
    bestMatchType: 'ESFP',
    bestMatchDescription: '파티를 즐기는 여행자',
    bestMatchImage: 'assets/esfp.png',
    bestMatchName: '하모',
    bestMatchRegion: '진주시',
    worstMatchType: 'ENFP',
    worstMatchDescription: '텐션 높은 인싸 여행자',
    worstMatchImage: 'assets/enfp.png',
    worstMatchName: '밀양아리랑',
    worstMatchRegion: '밀양시',
    traits: [
      '항상 모든 것을 계획하고 준비하는 타입',
      '시간과 일정에 철저히 따르는 성격',
      '예상치 못한 상황에 스트레스를 받을 수 있음',
      '여행 중 규칙과 질서를 중시',
    ],
    besttraits: [
      '사교적이고 활기찬 여행을 즐기는 타입',
      '다양한 사람들과 어울리며 즐거움을 찾음',
      '구체적인 계획 없이 자유롭게 여행',
      '파티와 축제 분위기를 선호',
    ],
    worsttraits: [
      '같이 여행가면 재밌는 타입',
      '구체적인 계획은 잘 안 짜는 타입',
      '즐거운 모임 자리에서 텐션 폭발',
      '혼자만의 시간도 필요해',
    ],
  ),
  MBTIData(
    type: 'ISFJ',
    description: '배려 넘치는 동행자',
    mascotImage: 'assets/isfj.png',
    mascotName: '하마니',
    mascotRegion: '함안군',
    bestMatchType: 'ESTP',
    bestMatchDescription: '스릴을 즐기는 모험가',
    bestMatchImage: 'assets/estp.png',
    bestMatchName: '천왕이',
    bestMatchRegion: '산청군',
    worstMatchType: 'ENTP',
    worstMatchDescription: '독창적인 아이디어 탐험가',
    worstMatchImage: 'assets/entp.png',
    worstMatchName: '토더기',
    worstMatchRegion: '김해시',
    traits: [
      '다른 사람들을 먼저 생각하고 챙기는 타입',
      '여행 중 편안함과 안정감을 중요시함',
      '갈등을 피하고 조화를 이루는 것을 좋아함',
      '작은 디테일도 놓치지 않음',
    ],
    besttraits: [
      '모험과 스릴을 즐기는 타입',
      '즉흥적이고 활기찬 여행을 선호',
      '단조로운 일정보다는 액티비티 중심의 여행을 좋아함',
      '새로운 경험에 두려움 없이 도전',
    ],
    worsttraits: [
      '새로운 아이디어와 경험을 찾아 떠나는 타입',
      '전통적인 여행보다는 독특하고 창의적인 여행을 선호',
      '즉흥적이며 규칙에 얽매이지 않는 스타일',
      '토론과 대화를 통해 여행 중에도 끊임없이 아이디어를 교환',
    ],
  ),
  MBTIData(
    type: 'INFJ',
    description: '내면을 탐구하는 여행자',
    mascotImage: 'assets/infj.png',
    mascotName: '아림&아름',
    mascotRegion: '거창군',
    bestMatchType: 'ENFP',
    bestMatchDescription: '텐션 높은 인싸 여행자',
    bestMatchImage: 'assets/enfp.png',
    bestMatchName: '밀양아리랑',
    bestMatchRegion: '밀양시',
    worstMatchType: 'ESTP',
    worstMatchDescription: '스릴을 즐기는 모험가',
    worstMatchImage: 'assets/estp.png',
    worstMatchName: '천왕이',
    worstMatchRegion: '산청군',
    traits: [
      '조용하고 깊이 있는 여행을 선호하는 타입',
      '관광지보다는 의미 있는 장소를 더 좋아함',
      '혼자만의 시간을 소중히 여기며 내면의 성장에 집중',
      '여행 중에도 깊은 대화를 즐김',
    ],
    besttraits: [
      '같이 여행가면 재밌는 타입',
      '구체적인 계획은 잘 안 짜는 타입',
      '즐거운 모임 자리에서 텐션 폭발',
      '혼자만의 시간도 필요해',
    ],
    worsttraits: [
      '모험과 스릴을 즐기는 타입',
      '즉흥적이고 활기찬 여행을 선호',
      '단조로운 일정보다는 액티비티 중심의 여행을 좋아함',
      '새로운 경험에 두려움 없이 도전',
    ],
  ),
  MBTIData(
    type: 'INTJ',
    description: '전략적인 미지 탐험가',
    mascotImage: 'assets/intj.png',
    mascotName: '홍의장군',
    mascotRegion: '의령군',
    bestMatchType: 'ENTP',
    bestMatchDescription: '독창적인 아이디어 탐험가',
    bestMatchImage: 'assets/entp.png',
    bestMatchName: '토더기',
    bestMatchRegion: '김해시',
    worstMatchType: 'ISFP',
    worstMatchDescription: '감성적인 자연 애호가',
    worstMatchImage: 'assets/isfp.png',
    worstMatchName: '다사돌',
    worstMatchRegion: '하동시',
    traits: [
      '효율적인 여행을 계획하는 타입',
      '미지의 장소를 탐험하고 새로운 지식을 얻는 것을 즐김',
      '단체 여행보다는 독립적인 여행을 선호',
      '목표 지향적인 여행 스타일',
    ],
    besttraits: [
      '새로운 아이디어와 경험을 찾아 떠나는 타입',
      '전통적인 여행보다는 독특하고 창의적인 여행을 선호',
      '즉흥적이며 규칙에 얽매이지 않는 스타일',
      '토론과 대화를 통해 여행 중에도 끊임없이 아이디어를 교환',
    ],
    worsttraits: [
      '자연과 예술을 사랑하는 타입',
      '평화롭고 아름다운 장소를 찾는 것을 좋아함',
      '자유롭고 즉흥적인 여행 스타일',
      '자신만의 감정에 충실하며 편안한 여행을 추구',
    ],
  ),
  MBTIData(
    type: 'ESTJ',
    description: '효율적인 여행 리더',
    mascotImage: 'assets/estj.png',
    mascotName: '해랑이',
    mascotRegion: '남해군',
    bestMatchType: 'ISFP',
    bestMatchDescription: '감성적인 자연 애호가',
    bestMatchImage: 'assets/isfp.png',
    bestMatchName: '하마니',
    bestMatchRegion: '함안군',
    worstMatchType: 'INFP',
    worstMatchDescription: '꿈을 찾아 떠나는 방랑자',
    worstMatchImage: 'assets/infp.png',
    worstMatchName: '피우미',
    worstMatchRegion: '창원시',
    traits: [
      '계획적이고 효율적으로 여행을 이끄는 타입',
      '시간 관리와 일정을 철저히 지킴',
      '단체 여행에서 리더 역할을 자처',
      '체계적이고 실용적인 여행 스타일',
    ],
    besttraits: [
      '자연과 예술을 사랑하는 타입',
      '평화롭고 아름다운 장소를 찾는 것을 좋아함',
      '자유롭고 즉흥적인 여행 스타일',
      '자신만의 감정에 충실하며 편안한 여행을 추구',
    ],
    worsttraits: [
      '영감과 감동을 주는 여행지를 찾는 타입',
      '자유롭고 창의적인 여행을 즐김',
      '타인의 이야기나 문화를 탐구하며 의미를 찾음',
      '여행 중에 자아를 발견하고자 함',
    ],
  ),
  MBTIData(
    type: 'ESFJ',
    description: '모두를 챙기는 세심한 동반자',
    mascotImage: 'assets/esfj.png',
    mascotName: '몽돌이&몽순이',
    mascotRegion: '거제시',
    bestMatchType: 'ISTP',
    bestMatchDescription: '즉흥적인 탐험가',
    bestMatchImage: 'assets/istp.png',
    bestMatchName: '고룡이',
    bestMatchRegion: '고성군',
    worstMatchType: 'INTP',
    worstMatchDescription: '깊이 있는 지식 탐구자',
    worstMatchImage: 'assets/intp.png',
    worstMatchName: '통멸이',
    worstMatchRegion: '통영시',
    traits: [
      '동행자들을 배려하며 여행을 주도하는 타입',
      '사람들과의 관계를 중시하며 조화로운 여행을 추구',
      '일정과 장소를 신중하게 선택해 모두가 만족하도록 노력',
      '사소한 부분까지도 신경 씀',
    ],
    besttraits: [
      '계획 없이 자유롭게 여행하는 타입',
      '액티비티와 모험을 즐김',
      '예상치 못한 상황을 즐기며 즉흥적인 결정에 능숙',
      '여행 중에도 실용성을 중시',
    ],
    worsttraits: [
      '지적 호기심을 만족시키기 위해 여행하는 타입',
      '역사적이거나 과학적인 장소를 선호',
      '여행 중에도 독립적인 사고와 탐구를 중요시함',
      '대규모 단체 여행보다 소규모나 개인 여행을 선호',
    ],
  ),
  MBTIData(
    type: 'ENFJ',
    description: '인연을 찾는 열정 여행자',
    mascotImage: 'assets/enfj.png',
    mascotName: '양이&산이',
    mascotRegion: '양산시',
    bestMatchType: 'INFP',
    bestMatchDescription: '꿈을 찾아 떠나는 방랑자',
    bestMatchImage: 'assets/infp.png',
    bestMatchName: '피우미',
    bestMatchRegion: '창원시',
    worstMatchType: 'ISTP',
    worstMatchDescription: '즉흥적인 탐험가',
    worstMatchImage: 'assets/istp.png',
    worstMatchName: '고룡이',
    worstMatchRegion: '고성군',
    traits: [
      '사람들과의 연결을 중시하며 여행하는 타입',
      '여행 중 새로운 인연을 만들고 관계를 형성하는 것을 즐김',
      '타인을 배려하고 이끌며 함께하는 여행을 선호',
      '긍정적인 에너지를 전파함',
    ],
    besttraits: [
      '영감과 감동을 주는 여행지를 찾는 타입',
      '자유롭고 창의적인 여행을 즐김',
      '타인의 이야기나 문화를 탐구하며 의미를 찾음',
      '여행 중에 자아를 발견하고자 함',
    ],
    worsttraits: [
      '계획 없이 자유롭게 여행하는 타입',
      '액티비티와 모험을 즐김',
      '예상치 못한 상황을 즐기며 즉흥적인 결정에 능숙',
      '여행 중에도 실용성을 중시',
    ],
  ),
  MBTIData(
    type: 'ENTJ',
    description: '목표 지향적인 정복자',
    mascotImage: 'assets/entj.png',
    mascotName: '물레동자&신비',
    mascotRegion: '함양시',
    bestMatchType: 'INTP',
    bestMatchDescription: '깊이 있는 지식 탐구자',
    bestMatchImage: 'assets/intp.png',
    bestMatchName: '통멸이',
    bestMatchRegion: '통영시',
    worstMatchType: 'ISFP',
    worstMatchDescription: '감성적인 자연 애호가',
    worstMatchImage: 'assets/isfp.png',
    worstMatchName: '다사돌',
    worstMatchRegion: '하동시',
    traits: [
      '목표를 세우고 이를 달성하는 여행을 좋아하는 타입',
      '계획적이고 체계적인 여행을 선호',
      '리더십을 발휘하여 단체 여행을 이끄는 역할',
      '여행 중에도 성취감을 추구',
    ],
    besttraits: [
      '지적 호기심을 만족시키기 위해 여행하는 타입',
      '역사적이거나 과학적인 장소를 선호',
      '여행 중에도 독립적인 사고와 탐구를 중요시함',
      '대규모 단체 여행보다 소규모나 개인 여행을 선호',
    ],
    worsttraits: [
      '자연과 예술을 사랑하는 타입',
      '평화롭고 아름다운 장소를 찾는 것을 좋아함',
      '자유롭고 즉흥적인 여행 스타일',
      '자신만의 감정에 충실하며 편안한 여행을 추구',
    ],
  ),
  MBTIData(
    type: 'ISTP',
    description: '즉흥적인 탐험가',
    mascotImage: 'assets/istp.png',
    mascotName: '고룡이',
    mascotRegion: '고성군',
    bestMatchType: 'ESFJ',
    bestMatchDescription: '모두를 챙기는 세심한 동반자',
    bestMatchImage: 'assets/esfj.png',
    bestMatchName: '몽돌이&몽순이',
    bestMatchRegion: '거제시',
    worstMatchType: 'ENFJ',
    worstMatchDescription: '인연을 찾는 열정 여행자',
    worstMatchImage: 'assets/enfj.png',
    worstMatchName: '양이&산이',
    worstMatchRegion: '양산시',
    traits: [
      '계획 없이 자유롭게 여행하는 타입',
      '액티비티와 모험을 즐김',
      '예상치 못한 상황을 즐기며 즉흥적인 결정에 능숙',
      '여행 중에도 실용성을 중시',
    ],
    besttraits: [
      '동행자들을 배려하며 여행을 주도하는 타입',
      '사람들과의 관계를 중시하며 조화로운 여행을 추구',
      '일정과 장소를 신중하게 선택해 모두가 만족하도록 노력',
      '사소한 부분까지도 신경 씀',
    ],
    worsttraits: [
      '사람들과의 연결을 중시하며 여행하는 타입',
      '여행 중 새로운 인연을 만들고 관계를 형성하는 것을 즐김',
      '타인을 배려하고 이끌며 함께하는 여행을 선호',
      '긍정적인 에너지를 전파함',
    ],
  ),
  MBTIData(
    type: 'ISFP',
    description: '감성적인 자연 애호가',
    mascotImage: 'assets/isfp.png',
    mascotName: '다시돌',
    mascotRegion: '하동시',
    bestMatchType: 'ESTJ',
    bestMatchDescription: '효율적인 여행 리더',
    bestMatchImage: 'assets/estj.png',
    bestMatchName: '해랑이',
    bestMatchRegion: '남해군',
    worstMatchType: 'ENTJ',
    worstMatchDescription: '목표 지향적인 정복자',
    worstMatchImage: 'assets/entj.png',
    worstMatchName: '물레동자&신비',
    worstMatchRegion: '함양군',
    traits: [
      '자연과 예술을 사랑하는 타입',
      '평화롭고 아름다운 장소를 찾는 것을 좋아함',
      '자유롭고 즉흥적인 여행 스타일',
      '자신만의 감정에 충실하며 편안한 여행을 추구',
    ],
    besttraits: [
      '계획적이고 효율적으로 여행을 이끄는 타입',
      '시간 관리와 일정을 철저히 지킴',
      '단체 여행에서 리더 역할을 자처',
      '체계적이고 실용적인 여행 스타일',
    ],
    worsttraits: [
      '목표를 세우고 이를 달성하는 여행을 좋아하는 타입',
      '계획적이고 체계적인 여행을 선호',
      '리더십을 발휘하여 단체 여행을 이끄는 역할',
      '여행 중에도 성취감을 추구',
    ],
  ),
  MBTIData(
    type: 'INFP',
    description: '꿈을 찾아 떠나는 방랑자',
    mascotImage: 'assets/infp.png',
    mascotName: '피우미',
    mascotRegion: '창원시',
    bestMatchType: 'ENFJ',
    bestMatchDescription: '인연을 찾는 열정 여행자',
    bestMatchImage: 'assets/enfj.png',
    bestMatchName: '양이&산이',
    bestMatchRegion: '양산시',
    worstMatchType: 'ESTJ',
    worstMatchDescription: '효율적인 여행 리더',
    worstMatchImage: 'assets/estj.png',
    worstMatchName: '해랑이',
    worstMatchRegion: '남해군',
    traits: [
      '영감과 감동을 주는 여행지를 찾는 타입',
      '자유롭고 창의적인 여행을 즐김',
      '타인의 이야기나 문화를 탐구하며 의미를 찾음',
      '여행 중에 자아를 발견하고자 함',
    ],
    besttraits: [
      '사람들과의 연결을 중시하며 여행하는 타입',
      '여행 중 새로운 인연을 만들고 관계를 형성하는 것을 즐김',
      '타인을 배려하고 이끌며 함께하는 여행을 선호',
      '긍정적인 에너지를 전파함',
    ],
    worsttraits: [
      '계획적이고 효율적으로 여행을 이끄는 타입',
      '시간 관리와 일정을 철저히 지킴',
      '단체 여행에서 리더 역할을 자처',
      '체계적이고 실용적인 여행 스타일',
    ],
  ),
  MBTIData(
    type: 'INTP',
    description: '깊이 있는 지식 탐구자',
    mascotImage: 'assets/intp.png',
    mascotName: '통멸이',
    mascotRegion: '통영시',
    bestMatchType: 'ENTJ',
    bestMatchDescription: '목표 지향적인 정복자',
    bestMatchImage: 'assets/entj.png',
    bestMatchName: '물레동자&신비',
    bestMatchRegion: '함양군',
    worstMatchType: 'ISFJ',
    worstMatchDescription: '배려 넘치는 동행자',
    worstMatchImage: 'assets/isfj.png',
    worstMatchName: '하마니',
    worstMatchRegion: '함안군',
    traits: [
      '지적 호기심을 만족시키기 위해 여행하는 타입',
      '역사적이거나 과학적인 장소를 선호',
      '여행 중에도 독립적인 사고와 탐구를 중요시함',
      '대규모 단체 여행보다 소규모나 개인 여행을 선호',
    ],
    besttraits: [
      '목표를 세우고 이를 달성하는 여행을 좋아하는 타입',
      '계획적이고 체계적인 여행을 선호',
      '리더십을 발휘하여 단체 여행을 이끄는 역할',
      '여행 중에도 성취감을 추구',
    ],
    worsttraits: [
      '다른 사람들을 먼저 생각하고 챙기는 타입',
      '여행 중 편안함과 안정감을 중요시함',
      '갈등을 피하고 조화를 이루는 것을 좋아함',
      '작은 디테일도 놓치지 않음',
    ],
  ),
  MBTIData(
    type: 'ESTP',
    description: '스릴을 즐기는 모험가',
    mascotImage: 'assets/estp.png',
    mascotName: '천왕이',
    mascotRegion: '산청군',
    bestMatchType: 'ISFP',
    bestMatchDescription: '감성적인 자연 애호가',
    bestMatchImage: 'assets/isfp.png',
    bestMatchName: '다사돌',
    bestMatchRegion: '하동시',
    worstMatchType: 'INFJ',
    worstMatchDescription: '내면을 탐구하는 여행자',
    worstMatchImage: 'assets/infj.png',
    worstMatchName: '아림&아름',
    worstMatchRegion: '거창군',
    traits: [
      '모험과 스릴을 즐기는 타입',
      '즉흥적이고 활기찬 여행을 선호',
      '단조로운 일정보다는 액티비티 중심의 여행을 좋아함',
      '새로운 경험에 두려움 없이 도전',
    ],
    besttraits: [
      '자연과 예술을 사랑하는 타입',
      '평화롭고 아름다운 장소를 찾는 것을 좋아함',
      '자유롭고 즉흥적인 여행 스타일',
      '자신만의 감정에 충실하며 편안한 여행을 추구',
    ],
    worsttraits: [
      '조용하고 깊이 있는 여행을 선호하는 타입',
      '관광지보다는 의미 있는 장소를 더 좋아함',
      '혼자만의 시간을 소중히 여기며 내면의 성장에 집중',
      '여행 중에도 깊은 대화를 즐김',
    ],
  ),
  MBTIData(
    type: 'ESFP',
    description: '파티를 즐기는 여행자',
    mascotImage: 'assets/esfp.png',
    mascotName: '하모',
    mascotRegion: '진주시',
    bestMatchType: 'ISTJ',
    bestMatchDescription: '꼼꼼한 계획형 여행자',
    bestMatchImage: 'assets/istj.png',
    bestMatchName: '또록이',
    bestMatchRegion: '사천시',
    worstMatchType: 'INTJ',
    worstMatchDescription: '전략적인 미지 탐험가',
    worstMatchImage: 'assets/intj.png',
    worstMatchName: '홍의장군',
    worstMatchRegion: '의령군',
    traits: [
      '사교적이고 활기찬 여행을 즐기는 타입',
      '다양한 사람들과 어울리며 즐거움을 찾음',
      '구체적인 계획 없이 자유롭게 여행',
      '파티와 축제 분위기를 선호',
    ],
    besttraits: [
      '항상 모든 것을 계획하고 준비하는 타입',
      '시간과 일정에 철저히 따르는 성격',
      '예상치 못한 상황에 스트레스를 받을 수 있음',
      '여행 중 규칙과 질서를 중시',
    ],
    worsttraits: [
      '효율적인 여행을 계획하는 타입',
      '미지의 장소를 탐험하고 새로운 지식을 얻는 것을 즐김',
      '단체 여행보다는 독립적인 여행을 선호',
      '목표 지향적인 여행 스타일',
    ],
  ),
  MBTIData(
    type: 'ENFP',
    description: '텐션 높은 인싸 여행자',
    mascotImage: 'assets/enfp.png',
    mascotName: '밀양아리랑',
    mascotRegion: '밀양시',
    bestMatchType: 'INFJ',
    bestMatchDescription: '내면을 탐구하는 여행자',
    bestMatchImage: 'assets/infj.png',
    bestMatchName: '아림&아름',
    bestMatchRegion: '거창군',
    worstMatchType: 'ISTJ',
    worstMatchDescription: '꼼꼼한 계획형 여행자',
    worstMatchImage: 'assets/istj.png',
    worstMatchName: '또록이',
    worstMatchRegion: '사천시',
    traits: [
      '같이 여행가면 재밌는 타입',
      '구체적인 계획은 잘 안 짜는 타입',
      '즐거운 모임 자리에서 텐션 폭발',
      '혼자만의 시간도 필요해',
    ],
    besttraits: [
      '조용하고 깊이 있는 여행을 선호하는 타입',
      '관광지보다는 의미 있는 장소를 더 좋아함',
      '혼자만의 시간을 소중히 여기며 내면의 성장에 집중',
      '여행 중에도 깊은 대화를 즐김',
    ],
    worsttraits: [
      '항상 모든 것을 계획하고 준비하는 타입',
      '시간과 일정에 철저히 따르는 성격',
      '예상치 못한 상황에 스트레스를 받을 수 있음',
      '여행 중 규칙과 질서를 중시',
    ],
  ),
  MBTIData(
    type: 'ENTP',
    description: '독창적인 아이디어 탐험가',
    mascotImage: 'assets/entp.png',
    mascotName: '토더기',
    mascotRegion: '김해시',
    bestMatchType: 'INTJ',
    bestMatchDescription: '전략적인 미지 탐험가',
    bestMatchImage: 'assets/intj.png',
    bestMatchName: '홍의장군',
    bestMatchRegion: '의령군',
    worstMatchType: 'ISFJ',
    worstMatchDescription: '배려 넘치는 동행자',
    worstMatchImage: 'assets/isfj.png',
    worstMatchName: '하마니',
    worstMatchRegion: '함안군',
    traits: [
      '새로운 아이디어와 경험을 찾아 떠나는 타입',
      '전통적인 여행보다는 독특하고 창의적인 여행을 선호',
      '즉흥적이며 규칙에 얽매이지 않는 스타일',
      '토론과 대화를 통해 여행 중에도 끊임없이 아이디어를 교환',
    ],
    besttraits: [
      '효율적인 여행을 계획하는 타입',
      '미지의 장소를 탐험하고 새로운 지식을 얻는 것을 즐김',
      '단체 여행보다는 독립적인 여행을 선호',
      '목표 지향적인 여행 스타일',
    ],
    worsttraits: [
      '다른 사람들을 먼저 생각하고 챙기는 타입',
      '여행 중 편안함과 안정감을 중요시함',
      '갈등을 피하고 조화를 이루는 것을 좋아함',
      '작은 디테일도 놓치지 않음',
    ],
  ),
];
